# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcm < Formula
  desc "Git Category Manager — organize branches without renaming them"
  homepage "https://github.com/SanghaviSiddhesh21/gcm"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/SanghaviSiddhesh21/gcm/releases/download/v0.1.5/gcm_0.1.5_darwin_amd64.tar.gz"
      sha256 "98ba608c5b3e6552878fd4b8e6998d91ef23305a11aa79680e7dd4cd8fb4df5c"

      def install
        bin.install "gcm"
      end
    end
    on_arm do
      url "https://github.com/SanghaviSiddhesh21/gcm/releases/download/v0.1.5/gcm_0.1.5_darwin_arm64.tar.gz"
      sha256 "6c9af4131ca562c16d573d26ac35dba3a4b1922363026751c498334eb758d43b"

      def install
        bin.install "gcm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SanghaviSiddhesh21/gcm/releases/download/v0.1.5/gcm_0.1.5_linux_amd64.tar.gz"
        sha256 "91cbfa1e30379b92d747f0739ddd1ddd83d975d9ab9bbfa09a71e3453d070af9"

        def install
          bin.install "gcm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SanghaviSiddhesh21/gcm/releases/download/v0.1.5/gcm_0.1.5_linux_arm64.tar.gz"
        sha256 "37c5b8463420a6fbdaa37e9bf00c9bd34ba797a8956400e4a92e604b9610ac0c"

        def install
          bin.install "gcm"
        end
      end
    end
  end
end
