# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcm < Formula
  desc "Git Category Manager — organize branches without renaming them"
  homepage "https://github.com/SanghaviSiddhesh21/gcm"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SanghaviSiddhesh21/gcm/releases/download/v0.1.8/gcm_0.1.8_darwin_amd64.tar.gz"
      sha256 "3e6fd2d670ed6a8fc750871a492e6c490a391a715b8224da508fd0c57df351b9"

      define_method(:install) do
        bin.install "gcm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SanghaviSiddhesh21/gcm/releases/download/v0.1.8/gcm_0.1.8_darwin_arm64.tar.gz"
      sha256 "ffaeb1a83e80adf06368bd7477f1bd3b759430720d2decb9806c531a79a26417"

      define_method(:install) do
        bin.install "gcm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SanghaviSiddhesh21/gcm/releases/download/v0.1.8/gcm_0.1.8_linux_amd64.tar.gz"
      sha256 "5df6929fffe953b2aaf282fe3737786517564f746bdd9f04110e94445998e877"
      define_method(:install) do
        bin.install "gcm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SanghaviSiddhesh21/gcm/releases/download/v0.1.8/gcm_0.1.8_linux_arm64.tar.gz"
      sha256 "2d1ea274748e8679095344d12a6a6117348a5adb4ff8af0e8516a9ed45dcabc6"
      define_method(:install) do
        bin.install "gcm"
      end
    end
  end
end
